### ISSUE TITLE
Sorry ms nop but I wanted to know something about the pc

### ISSUE THREAD

**Issue by BeanieMen** [nopeless/uwufier#3]
As you know you have bought the pc, if I plan to like buy a pc in the future can I sell your pc

**Comment by nopeless** [comment]
Yes. Its yours. I hope you get a better pc :)

**Comment by BeanieMen** [comment]
> Yes. Its yours. I hope you get a better pc :)

❤️

**Comment by BeanieMen** [comment]
I couldn't sell it

**Comment by BeanieMen** [comment]
I will still buy a new pc, already have 800$ saved up for it
